version: 2.1
workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - aws
jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          command: echo $AWS_ACCESS_KEY_ID
