version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.1.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id:  AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: aws
          create-repo: true
          path: ./backend
          region: "ap-northeast-1"
          registry-id: AWS_ID
          repo: "tf-app"
          repo-scan-on-push: true
          skip-when-tags-exist: false
          tag: 'latest'
          extra-build-args: '--build-arg RAILS_MASTER_KEY=${RAILS_MASTER_KEY}'